const Images = {
  aldar: 'static/images/aldar.png',
  certificate: 'static/images/certificate.png',
  avatarDefault: 'static/images/avatar.png',
  avatar: {
    body: {
      body1: 'static/images/avatar/body-1.svg',
      body2: 'static/images/avatar/body-2.svg',
      body3: 'static/images/avatar/body-3.svg',
      body4: 'static/images/avatar/body-4.svg',
      body6: 'static/images/avatar/body-6.svg',
    },
    eyes: {
      eyes1: 'static/images/avatar/eyes-1.svg',
      eyes2: 'static/images/avatar/eyes-2.svg',
      eyes3: 'static/images/avatar/eyes-3.svg',
      eyes5: 'static/images/avatar/eyes-5.svg',
      eyes4: 'static/images/avatar/eyes-4.svg',
      eyes6: 'static/images/avatar/eyes-6.svg',
    },
    mouth: {
      mouth1: 'static/images/avatar/mouth-1.svg',
      mouth2: 'static/images/avatar/mouth-2.svg',
      mouth3: 'static/images/avatar/mouth-3.svg',
      mouth5: 'static/images/avatar/mouth-5.svg',
      mouth4: 'static/images/avatar/mouth-4.svg',
      mouth6: 'static/images/avatar/mouth-6.svg',
    },
  },
  skillBox: {
    closed: 'static/images/treasure/closed.png',
    opened: 'static/images/treasure/opened.png',
    skill: 'static/images/treasure/skill.png',
    arrow: 'static/images/treasure/arrow.png',
  },
  sidemenu: {
    prices: 'static/images/prices-icon.svg',
    courses: 'static/images/courseslibrary-icon.svg',
    contests: 'static/images/contests-icon.svg',
    news: 'static/images/notifications-icon.svg',
    rating: 'static/images/rating-icon.svg',
    profile: 'static/images/profile-icon.svg',
    learn: 'static/images/learning-icon.svg',
    faculties: 'static/images/faculties-icon.svg',
    instagram: 'static/images/instagram-icon.svg',
    youtube: 'static/images/youtube-icon.svg',
    school: 'static/images/school.svg',
  },
  boxMaterial: 'static/images/box_material.png',
  chapterImage: 'static/images/chapter_image.jpg',
  clockAboutLanding: 'static/images/clock_about_landing.png',
  coin: 'static/images/coin.gif',
  compMaterial: 'static/images/comp_material.png',
  contests: 'static/images/contest.svg',
  courseIcon: 'static/images/courseIcon.svg',
  courseIconGrey: 'static/images/courseIconGrey.svg',
  dirt: 'static/images/dirt.svg',
  facultyBackgroundPlaceholder: 'static/images/faculty_background_placeholder.svg',
  facultyIcon: 'static/images/facultyIcon.svg',
  facultyIconColored: 'static/images/facultyIconColored.svg',
  facultyIconGrey: 'static/images/facultyIconGrey.svg',
  facultyIconPng: 'static/images/facultyIcon.png',
  facultyPlaceholder: 'static/images/faculty_placeholder.svg',
  laptop: 'static/images/laptop.png',
  letterX: 'static/images/letter-x.svg',
  lineMenu: 'static/images/line-menu.svg',
  locker: 'static/images/locker.svg',
  loginIcon: 'static/images/loginIcon.svg',
  logotype: 'static/images/logotype.svg',
  logoutIcon: 'static/images/logoutIcon.svg',
  ovalEmpty: 'static/images/oval_empty.png',
  ovalFull: 'static/images/oval_full.png',
  pencilAboutLanding: 'static/images/pencil_about_landing.png',
  peopleAboutLanding: 'static/images/people_about_landing.png',
  personAboutLanding: 'static/images/person_about_landing.png',
  platformsImage: 'static/images/platforms_image.png',
  playIcon: 'static/images/playIcon.svg',
  pointsIcon: 'static/images/pointsIcon.svg',
  ratingIcon: 'static/images/ratingIcon.svg',
  smileGrey: 'static/images/smile_grey.png',
  webinarImage: 'static/images/webinar_image.png',
  webinarLink: 'static/images/webinarLink.svg',
  webinarLinkPng: 'static/images/webinarLink.png',
  webinarMaterial: 'static/images/webinar_material.png',
  workMaterial: 'static/images/work_material.png',
  sertificate: 'static/images/sertificate.png',
  wupai: {
    gif: 'static/images/coin.gif',
  },
};

export default Images;
